SET @now_ms = FLOOR(UNIX_TIMESTAMP(NOW(3)) * 1000);

SET @pinnacle_default_leagues = JSON_ARRAY(
    '芬兰 - 全国联赛',
    '芬兰 - 杯赛',
    '英格兰 - 超级联赛',
    '英格兰 - 冠军联赛',
    '英格兰 - 甲级联赛',
    '英格兰 - 乙级联赛',
    '意大利 - 甲级联赛',
    '意大利 - 乙级联赛',
    '德国 - 德甲',
    '德国 - 德乙',
    '西班牙 - 西甲',
    '西班牙 - 乙级联赛',
    '法国 - 甲级联赛',
    '法国 - 乙级联赛',
    '荷兰 - 甲级联赛',
    '荷兰 - 乙级联赛',
    '葡萄牙 - 超级联赛',
    '葡萄牙 - 甲级联赛',
    '芬兰 - 足球超级联赛A',
    '瑞典 - 超级联赛',
    '瑞典 - 甲级联赛',
    '爱尔兰超级联赛',
    '爱尔兰 - 甲级联赛',
    '奥地利 - 甲级联赛',
    '奥地利 - 乙级联赛',
    '瑞士 - 超级联赛',
    '瑞士 - 挑战联赛',
    '丹麦 - 超级联赛',
    '丹麦 - 甲级联赛',
    '挪威 - 足球超级联赛',
    '俄罗斯超级联赛',
    '比利时 - 职业联赛',
    '土耳其 - 超级联赛',
    '希腊超级联赛',
    '苏格兰 - 足球超级联赛',
    '波兰 - 超级联赛',
    '捷克 - 甲级联赛',
    '罗马尼亚 - 甲级联赛',
    '冰岛超级联赛',
    '乌克兰超级联赛',
    '巴西 - 甲级联赛',
    '巴西 - 乙级联赛',
    '阿根廷 - 职业联赛',
    '智利 - 甲级联赛',
    '哥伦比亚 - 甲级联赛',
    '厄瓜多尔 - 甲级联赛',
    '秘鲁 - 足球甲级联赛',
    '巴拉圭 - 职业联赛',
    '美国 - 美国足球大联盟',
    '美国 - USL锦标赛',
    '墨西哥 - 足球甲级联赛',
    '墨西哥 - 墨西哥足球拓展联赛',
    '日本 - J联赛',
    'Japan - J2/J3 League',
    '澳大利亚 - 甲级联赛',
    '澳大利亚 - NPL维多利亚州',
    '澳大利亚 - 甲级联赛女子',
    '韩国 - K联赛1',
    '沙特阿拉伯 - 职业联赛',
    '印度 - 超级联赛',
    '印度尼西亚 - 超级联赛',
    '巴林 - 超级联赛',
    '阿联酋 - 职业联赛',
    '中国 - 超级联赛',
    '埃及 - 超级联赛',
    'FIFA - 世界杯',
    '欧足联 - 冠军联赛',
    '欧足联 - 欧罗巴联赛',
    '欧足联 - 欧洲协会联赛',
    '英格兰足总杯',
    '德国杯赛',
    '意大利 - 杯赛',
    '奥地利 - 杯赛',
    '波兰 - 杯赛',
    '南美足联 - 解放者杯',
    '南美足协 - 南美俱乐部杯',
    '阿根廷 - 杯赛',
    '美国 - 公开杯'
);

SET @crown_default_leagues = JSON_ARRAY(
    '芬兰甲组联赛',
    '卡塔尔甲组联赛',
    '英格兰联赛杯',
    '英格兰联赛锦标赛',
    '西班牙杯',
    '法国杯',
    '荷兰KNVB杯',
    '葡萄牙杯',
    '俄罗斯杯',
    '丹麦杯',
    '挪威杯',
    '瑞典杯',
    '比利时杯',
    '土耳其杯',
    '希腊杯',
    '苏格兰足总杯',
    '罗马尼亚杯',
    '捷克杯',
    '乌克兰杯',
    '冰岛超级杯',
    '冰岛联赛杯',
    '巴西杯',
    '智利联赛杯',
    '中北美洲及加勒比海冠军杯',
    '亚足联冠军精英联赛',
    '亚足联冠军联赛二',
    '澳大利亚杯',
    '澳大利亚杯外围赛',
    '沙特国王杯',
    '卡塔尔联赛杯',
    '阿联酋总统杯',
    '阿联酋足总杯',
    '巴林超级杯',
    '埃及联赛杯',
    '埃及杯',
    '世界杯2026洲际(在墨西哥)',
    '欧美杯2026(在卡塔尔)',
    '世界杯2026欧洲外围赛',
    '欧洲国家联赛',
    '非洲国家杯2027外围赛',
    '国际友谊赛',
    '国际系列',
    '英格兰超级联赛',
    '英格兰冠军联赛',
    '英格兰甲组联赛',
    '英格兰乙组联赛',
    '意大利甲组联赛',
    '意大利乙组联赛',
    '德国甲组联赛',
    '德国乙组联赛',
    '西班牙甲组联赛',
    '西班牙乙组联赛',
    '法国甲组联赛',
    '法国乙组联赛',
    '荷兰甲组联赛',
    '荷兰乙组联赛',
    '葡萄牙超级联赛',
    '葡萄牙甲组联赛',
    '芬兰超级联赛',
    '瑞典超级联赛',
    '瑞典超级甲组联赛',
    '爱尔兰超级联赛',
    '爱尔兰甲组联赛',
    '奥地利甲组联赛',
    '奥地利乙组联赛',
    '瑞士超级联赛',
    '瑞士甲组联赛',
    '丹麦超级联赛',
    '丹麦甲组联赛',
    '挪威超级联赛',
    '俄罗斯超级联赛',
    '比利时甲组联赛A',
    '土耳其超级联赛',
    '希腊超级联赛甲组',
    '苏格兰超级联赛',
    '波兰超级联赛',
    '捷克甲组联赛',
    '罗马尼亚甲组联赛',
    '冰岛超级联赛',
    '乌克兰超级联赛',
    '巴西甲组联赛',
    '巴西乙组联赛',
    '阿根廷职业联赛',
    '智利甲组联赛',
    '哥伦比亚甲组联赛',
    '厄瓜多尔甲组联赛',
    '秘鲁甲组联赛',
    '巴拉圭甲组联赛',
    '美国职业大联盟',
    '美国足球冠军联赛',
    '墨西哥超级联赛',
    '墨西哥甲组联赛',
    '日本J1百年构想联赛',
    '日本J2 J3百年构想联赛',
    '澳大利亚甲组联赛',
    '澳大利亚维多利亚国家超级联赛',
    '澳大利亚女子甲组联赛',
    '韩国K甲组联赛',
    '沙特超级联赛',
    '印度超级联赛',
    '印尼超级联赛',
    '巴林超级联赛',
    '阿联酋超级联赛',
    '中国超级联赛',
    '埃及超级联赛',
    '世界杯2026(美加墨)',
    '欧洲冠军联赛',
    '欧洲联赛',
    '欧洲协会联赛',
    '英格兰足总杯',
    '德国杯',
    '意大利杯',
    '奥地利杯',
    '波兰杯',
    '南美自由杯',
    '南美洲球会杯',
    '阿根廷杯',
    '美国公开赛冠军杯'
);

INSERT INTO system_config (config_key, config_value, description, created_at, updated_at)
VALUES
    (
        'odds_monitor.selected_leagues',
        CAST(JSON_ARRAY() AS CHAR),
        '全平台赔率监控默认追踪显示清单，保留为空并由平台清单合并生成',
        @now_ms,
        @now_ms
    ),
    (
        'odds_monitor.selected_leagues.pinnacle',
        CAST(@pinnacle_default_leagues AS CHAR),
        '全平台赔率监控平博默认比赛清单',
        @now_ms,
        @now_ms
    ),
    (
        'odds_monitor.selected_leagues.crown',
        CAST(@crown_default_leagues AS CHAR),
        '全平台赔率监控皇冠默认比赛清单',
        @now_ms,
        @now_ms
    )
ON DUPLICATE KEY UPDATE
    config_value = VALUES(config_value),
    description = VALUES(description),
    updated_at = VALUES(updated_at);

INSERT INTO odds_data_source_configs (
    source_key,
    display_name,
    enabled,
    username,
    password,
    query_keyword,
    interval_seconds,
    created_at,
    updated_at
)
VALUES
    ('pinnacle', '平博', 0, NULL, NULL, 'ps3838.com', 60, @now_ms, @now_ms),
    ('crown', '皇冠', 0, NULL, NULL, 'https://m407.mos077.com/', 60, @now_ms, @now_ms)
ON DUPLICATE KEY UPDATE
    display_name = VALUES(display_name),
    query_keyword = CASE
        WHEN query_keyword IS NULL OR TRIM(query_keyword) = '' THEN VALUES(query_keyword)
        ELSE query_keyword
    END,
    interval_seconds = GREATEST(interval_seconds, 10),
    updated_at = VALUES(updated_at);

UPDATE odds_data_source_configs
SET enabled = 1,
    updated_at = @now_ms
WHERE source_key IN ('pinnacle', 'crown')
  AND username IS NOT NULL
  AND TRIM(username) <> ''
  AND password IS NOT NULL
  AND TRIM(password) <> '';
