CREATE TABLE IF NOT EXISTS auto_betting_intents (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    dedupe_key VARCHAR(255) NOT NULL,
    signal_source VARCHAR(64) NOT NULL,
    account_key VARCHAR(64) NOT NULL,
    league_name VARCHAR(128) NOT NULL,
    match_title VARCHAR(255) NOT NULL,
    market_type VARCHAR(32) NOT NULL,
    line_value VARCHAR(32) NULL,
    selection_name VARCHAR(64) NOT NULL,
    reference_source_key VARCHAR(32) NOT NULL,
    target_source_key VARCHAR(32) NOT NULL,
    reference_odds DECIMAL(18, 8) NOT NULL,
    target_odds DECIMAL(18, 8) NOT NULL,
    target_decimal_odds DECIMAL(18, 8) NOT NULL,
    decimal_edge DECIMAL(18, 8) NOT NULL,
    stake_amount DECIMAL(18, 4) NOT NULL,
    status VARCHAR(32) NOT NULL,
    reject_reason VARCHAR(64) NULL,
    captured_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    INDEX idx_auto_betting_intents_created (created_at),
    INDEX idx_auto_betting_intents_status (status),
    INDEX idx_auto_betting_intents_account_status (account_key, status),
    INDEX idx_auto_betting_intents_dedupe_status (dedupe_key, status)
);
