import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

describe('crown betting pages source', () => {
  const pagePath = join(process.cwd(), 'src', 'pages', 'CrownBetting.tsx')
  const historyPath = join(process.cwd(), 'src', 'pages', 'BettingHistory.tsx')
  const appSource = readFileSync(join(process.cwd(), 'src', 'App.tsx'), 'utf8')
  const layoutSource = readFileSync(join(process.cwd(), 'src', 'components', 'Layout.tsx'), 'utf8')

  it('adds crown betting and betting history routes below crown league selection', () => {
    expect(appSource).toContain("import('./pages/CrownBetting')")
    expect(appSource).toContain("import('./pages/BettingHistory')")
    expect(appSource).toContain('path="/crown-betting"')
    expect(appSource).toContain('path="/betting-history"')

    const crownFilterIndex = layoutSource.indexOf('/crown-league-filter')
    const crownBettingIndex = layoutSource.indexOf('/crown-betting')
    const bettingHistoryIndex = layoutSource.indexOf('/betting-history')
    expect(crownFilterIndex).toBeGreaterThan(-1)
    expect(crownBettingIndex).toBeGreaterThan(crownFilterIndex)
    expect(bettingHistoryIndex).toBeGreaterThan(crownBettingIndex)
  })

  it('lets crown betting add AdsPower accounts and detect account status and balance', () => {
    expect(existsSync(pagePath)).toBe(true)
    const source = readFileSync(pagePath, 'utf8')

    expect(source).toContain('皇冠投注')
    expect(source).toContain('监控保持本地浏览器直连，投注检测和执行只走 AdsPower 环境。')
    expect(source).toContain('监控账号不进入投注区')
    expect(source).toContain('添加皇冠账号')
    expect(source).toContain('账号状态')
    expect(source).toContain('账号余额')
    expect(source).toContain('待检测')
    expect(source).toContain('检测中')
    expect(source).toContain('检测一次')
    expect(source).toContain('正在检测 AdsPower 环境状态')
    expect(source).toContain('AdsPower 环境未打开')
    expect(source).toContain('登录网站')
    expect(source).toContain('loginUrl')
    expect(source).toContain('https://m407.mos077.com/')
    expect(source).not.toContain('/odds-monitor/crown/accounts/check')
    expect(source).not.toContain('登录密码')
    expect(source).not.toContain('Input.Password')
    expect(source).not.toContain('password: values.password')
    expect(source).toContain('在线')
    expect(source).toContain('账号在线，余额已获取')
    expect(source).toContain('异常')
    expect(source).toContain('自动化接入投注功能')
    expect(source).toContain('赛前')
    expect(source).toContain('滚球')
    expect(source).toContain('自动投注')
    expect(source).toContain('自动监听中')
    expect(source).toContain('自动投注结果')
    expect(source).not.toContain('运行实际测试')
    expect(source).not.toContain('PlayCircleOutlined')
    expect(source).toContain('保存设置')
    expect(source).toContain('crown-betting-automation-settings')
    expect(source).not.toContain('模拟模式')
    expect(source).not.toContain('运行模拟投注')
    expect(source).not.toContain('多账号模拟结果')
    expect(source).not.toContain('模拟赔率')
    expect(source).not.toContain('尚未运行模拟投注')
    expect(source).toContain('每号金额限制')
    expect(source).toContain('投注上限')
    expect(source).not.toContain('赔率波动容忍')
    expect(source).not.toContain('最低赔率优势')
    expect(source).toContain('最低投注水位')
    expect(source).toContain('信号有效期(秒)')
    expect(source).toContain('maxSignalAgeSeconds')
    expect(source).toContain('AdsPower 档案 ID')
    expect(source).toContain('检测 AdsPower')
    expect(source).toContain('打开环境')
    expect(source).toContain('/auto-betting/adspower/status')
    expect(source).toContain('/auto-betting/adspower/start-profile')
    expect(source).toContain('/auto-betting/adspower/crown-session')
    expect(source).toContain('/auto-betting/adspower/crown-session/match')
    expect(source).toContain("import { extractApiErrorMessage } from '../utils/apiError'")
    expect(source).toContain('extractApiErrorMessage(error,')
    expect(source).toContain('matchAdsPowerCrownSession')
    expect(source).toContain('/auto-betting/signals/odds-monitor/execute-crown-queue')
    expect(source).not.toContain('/auto-betting/intents/${decision.id}/execute-crown')
    expect(source).toContain('crownHistoryVerified')
    expect(source).toContain('crownBetReference')
    expect(source).toContain('已下注')
    expect(source).toContain('后端队列执行')
    expect(source).toContain('下注队列已完成，成功记录已写入后端')
    expect(source).toContain('本轮信号已执行完毕，不再重复重试')
    expect(source).not.toContain('下注成功，已核对皇冠投注历史')
    expect(source).toContain('/odds-monitor/alerts/list')
    expect(source).toContain('executeLatestCrownSignal')
    expect(source).toContain('attemptedSignalAtRef')
    expect(source).toContain('候选信号盘口')
    expect(source).toContain('采集系统合格回传')
    expect(source).toContain('按投注顺序排队')
    expect(source).toContain('正在投注盘口')
    expect(source).toContain('队列 #')
    expect(source).toContain('水位变化')
    expect(source).toContain('bettingMode: activeSignal.bettingMode')
    expect(source).toContain('matchPhase: activeSignal.matchPhase')
    expect(source).toContain('accountDisplayName: row.accountName')
    expect(source).toContain("row.matchPhase === 'prematch'")
    expect(source).toContain('未绑定 AdsPower 档案')
    expect(source).toContain("account.adsPowerStatus === 'opened'")
    expect(source).toContain("account.status === 'success'")
    expect(source).toContain('buildAutoBettingExecutionPlan')
    expect(source).toContain('extractCrownAlertSignalCandidates')
    expect(source).toContain('filterFreshCrownAlertSignals')
    expect(source).not.toContain('buildAutoBettingSimulation')
    expect(source).not.toContain('crownBettingSimulation')
    expect(source).not.toContain('阿森纳 vs 切尔西')
    expect(source).not.toContain('国际米兰 vs 尤文图斯')
    expect(source).toContain('删除账号')
    expect(source).toContain('crown-betting-accounts')
    expect(source).toContain('updateAutoBettingEnabled')
    expect(source).toContain('localStorage')
    expect(source).not.toContain('DATA_SOURCE_ACCOUNT_ID')
    expect(source).not.toContain('/odds-monitor/data-sources/configs/list')
    expect(source).not.toContain('createAccountFromDataSource')
    expect(source).not.toContain("rules={[{ required: true, message: '请输入 AdsPower 档案 ID' }]}")
    expect(source).not.toContain('name="status"')
    expect(source).not.toContain('name="balance"')
  })

  it('selects the next runnable signal before showing running state', () => {
    const source = readFileSync(pagePath, 'utf8')
    const signalSelectionIndex = source.indexOf('selectNextCrownAlertSignal(qualifiedCandidates')
    const runningStateIndex = source.indexOf('setExecutionRunning(true)')

    expect(source).not.toContain('processedSignalKeysRef')
    expect(source).not.toContain('Date.now() - lastAttemptAt < AUTO_BETTING_SIGNAL_RETRY_COOLDOWN_MS')
    expect(signalSelectionIndex).toBeGreaterThan(-1)
    expect(runningStateIndex).toBeGreaterThan(signalSelectionIndex)
  })

  it('does not seed hard-coded crown accounts into production storage', () => {
    const source = readFileSync(pagePath, 'utf8')

    expect(source).not.toContain('SHOULD_SEED_BETTING_ACCOUNTS')
    expect(source).not.toContain('seededBettingAccounts')
    expect(source).not.toContain('buildSeededBettingAccounts')
    expect(source).not.toContain('mergeSeededBettingAccounts')
  })

  it('keeps crown account table fields grouped and compact', () => {
    expect(existsSync(pagePath)).toBe(true)
    const source = readFileSync(pagePath, 'utf8')

    expect(source).toContain('账号与 AdsPower 环境')
    expect(source).toContain('账号状态')
    expect(source).toContain('检测结果')
    expect(source).toContain('每个账号绑定一个独立 AdsPower 环境')
    expect(source).toContain('余额未返回')
    expect(source).toContain('检测一次')
    expect(source).toContain('登录账号：')
    expect(source).toContain('更新：')
    expect(source).toContain('accountGridStyle')
    expect(source).toContain('compactAccountCardStyles')
    expect(source).toContain("padding: '10px 16px 12px'")
    expect(source).toContain("padding: '8px 0'")
    expect(source).not.toContain('盘口抓取')
    expect(source).not.toContain('抓取检测')
    expect(source).not.toContain('<Table')
    expect(source).not.toContain("title: '登录网站'")
    expect(source).not.toContain("title: '更新时间'")
    expect(source).not.toContain("title: '备注'")
    expect(source).not.toContain('scroll={{ x: 820 }}')
    expect(source).not.toContain('extra={<Tag color="processing">账号状态</Tag>}')
  })

  it('loads full status betting records', () => {
    expect(existsSync(historyPath)).toBe(true)
    const source = readFileSync(historyPath, 'utf8')

    expect(source).toContain('下注记录')
    expect(source).toContain('/auto-betting/intents/recent')
    expect(source).toContain('全状态记录')
    expect(source).toContain('暂无下注记录')
    expect(source).toContain('失败/跳过')
    expect(source).toContain("dataIndex: 'reason'")
    expect(source).toContain('crownHistoryVerified')
    expect(source).toContain('crownHistoryCheckedAt')
    expect(source).toContain('crownBetReference')
    expect(source).toContain('AutoBettingIntentRow')
    expect(source).toContain('accountDisplayName')
    expect(source).toContain('readStoredCrownAccounts')
    expect(source).toContain('TELEGRAM_BETTING_SUCCESS_TYPE')
    expect(source).toContain('投注成功机器人')
    expect(source).toContain('添加机器人')
    expect(source).toContain('telegram_betting_success')
    expect(source).toContain('selectedAccountId')
    expect(source).toContain('filteredRows')
    expect(source).toContain('已导入账号')
    expect(source).toContain('全部账号')
    expect(source).toContain('bettingMode: string')
    expect(source).toContain('matchPhase: string')
    expect(source).toContain('phaseLabel')
    expect(source).toContain("import { extractApiErrorMessage } from '../utils/apiError'")
    expect(source).toContain('extractApiErrorMessage(error,')
    expect(source).not.toContain('/auto-betting/intents/verified-placed')
    expect(source).not.toContain('待下注')
    expect(source).not.toContain('已通过')
    expect(source).not.toContain('sampleRows')
    expect(source).not.toContain("id: 'bet-001-a'")
    expect(source).not.toContain('盈利情况')
  })
})
